Feature/df 2733 notice for contacted candidates
alv-ch/candidate-service pull request #186
Opened 2020-09-03 11:04 UTC by mdavidovski

2020-09-04 12:24 UTC, seco-mgabor requested changes

2020-09-08 09:01 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/logging/BusinessLogConstants.java
> +public interface BusinessLogConstants {
Not sure, why this should be a bad practice, but I did this also in the shared library: https://github.com/alv-ch/alv-shared-library/blob/master/alv-logger-starter/src/main/java/ch/admin/seco/alv/shared/logger/business/BusinessLogContext.java

2020-09-08 09:06 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/logging/BusinessLogEventType.java
>  public enum BusinessLogEventType implements BusinessLogEnum {
It is not related with this pull request. It is done according to the definition of the shared library I did. Here we would need a change in this library.

2020-09-08 09:10 UTC, seco-mgabor commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/logging/BusinessLogConstants.java
> +public interface BusinessLogConstants {
> According to Joshua Bloch, author of "Effective Java":
The constant interface pattern is a poor use of interfaces.
That a class uses some constants internally is an implementation detail.
Implementing a constant interface causes this implementation detail to leak into the class's exported API. It is of no consequence to the users of a class that the class implements a constant interface. In fact, it may even confuse them. Worse, it represents a commitment: if in a future release the class is modified so that it no longer needs to use the constants, it still must implement the interface to ensure binary compatibility. If a nonfinal class implements a constant interface,
all of its subclasses will have their namespaces polluted by the constants in the interface.

2020-09-08 09:26 UTC, seco-mgabor commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/logging/BusinessLogEventType.java
>  public enum BusinessLogEventType implements BusinessLogEnum {
I don't think you need to change ALV Shared Library for that.
Simply just remove the redundant names and let enumName() return Enum's name() result.
`public enum BusinessLogEventType implements BusinessLogEnum {
    CANDIDATE_PROFILE_ACCESS,
    CANDIDATE_CONTACT_MESSAGE,
    CANDIDATE_CONTACT_CREATE,
    CANDIDATE_CONTACT_REMOVE_OLD;

    @Override
    public String enumName() {
        return name();
    }
}
`

2020-09-08 14:34 UTC, palsch commented on candidate-app/src/main/resources/config/liquibase/changelog/2020071518000000_add_candidate_contact_table.xml
> +            <column name="job_offeror_type" type="varchar(12)">
Warum musst du hier den Type abspeichern? Wo wird dieser benötigt? Reicht es nicht, diesen anhand von der Rolle (z.B. ROLE_COMPANY) aus dem Security Context zu holen?

2020-09-08 14:43 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/UserNotAuthenticatedException.java
> +
For this case Spring uses AuthenticationException.
It would make sence to use it here too.

2020-09-08 16:31 UTC, palsch requested changes

2020-09-08 20:26 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/domain/candidate/CandidateContact.java
> +    @Column(name = "job_offeror_id")
I can change it, but then we need to think of something better.
The job offeror can be a PAV or a Company...

2020-09-08 20:29 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/domain/candidate/CandidateContact.java
> +
If possible, I would leave it like this for now, since this name is already all throughout the backend and fronted. Changing it would take me several hours (which I would rather use testing so we can put this feature on staging), and this is the name we chose in when we created the concept, 
https://alv-ch.atlassian.net/wiki/spaces/JR2/pages/1052180481/Konzept+Candidate+contact

2020-09-08 20:33 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/domain/enums/JobOfferorType.java
> +
Yes, that is how I get the info and make the mapping.
What we were thinking is to keep Job offeror type and User roles separate from a business logic perspective. And a user can have multiple roles, but a candidate contact can have only one type.
My idea was simply to keep data about which type of job offeror usually contacts a certain type of candidate (maybe in the future we don't delete them and make a statistic...). But we can talk about it, it's easy to remove the whole thing

2020-09-08 20:36 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/CandidateService.java
That is code from master. I added a CandidateContactMapper as a spring component as well to keep it consistent

2020-09-08 20:37 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/ContactCandidateService.java
> +
For consistency reasons... but again, we can talk about it and I can remove it easily

2020-09-08 20:40 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/ContactCandidateService.java
Consistency reasons... most of the time throughout the code we Integer, and not int

2020-09-08 20:50 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/elasticsearch/ElasticsearchCandidateSearchService.java
Again, for consistency reasons

2020-09-08 20:57 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/mapper/CandidateContactMapper.java
> +                case AuthoritiesConstants.PRIVATE_EMPLOYMENT_AGENT: return JobOfferorType.PAV;
That wouldn't make sense... here I'm trying to filter out everything that is not Pav or Company.
And  "UNKNOWN" or "INVALID" would mess that up

2020-09-08 21:00 UTC, mdavidovski commented on candidate-app/src/main/resources/config/application.yml
> +        cron: 0 0 * * * *
Yes

2020-09-08 21:03 UTC, mdavidovski commented on candidate-app/src/main/resources/config/liquibase/changelog/2020071518000000_add_candidate_contact_table.xml
> +            <column name="job_offeror_type" type="varchar(12)">
As I said, we wanted to make a distinction between an authority and a job offeror type from a business perspective. And I save it because it seemed to me like an interesting piece of information. We can talk about it, and maybe we can remove it completely

2020-09-21 13:20 UTC, seco-mgabor commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/elasticsearch/ElasticsearchCandidateSearchService.java
> +        CurrentUser currentUser = getCurrentUser().orElse(null);
Optional wäre auch eine Option :)

2020-09-21 13:20 UTC, seco-mgabor approved these changes

2020-09-22 10:10 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/ContactCandidateService.java
> +    private void sendMail(AnonymousContactMessageDTO anonymousContactMessage, Candidate candidate) {
Please clarify why it is called anonymous contact message and add here the javadoc

2020-09-22 10:21 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/CandidateService.java
> +    private CandidateContact getLatestCandidateContact(UUID candidateId) {
Could you describe it more detailed, why candidate contact is null

2020-09-22 10:55 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/mapper/CandidateContactMapper.java
> +            .setJobOfferorId(UUID.fromString(currentUser.getUserId()))
can current user also be "null"?

2020-09-22 10:58 UTC, palsch commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/elasticsearch/ElasticsearchCandidateSearchService.java
> +        return elasticsearchTemplate.query(searchQuery, response -> extractSearchResult(pageable, response));
Why did you replaced "queryForPage" with "query"?

2020-09-22 11:07 UTC, mdavidovski commented on candidate-app/src/main/java/ch/admin/seco/service/candidate/service/candidate/impl/mapper/CandidateContactMapper.java
> +            .setJobOfferorId(UUID.fromString(currentUser.getUserId()))
No, since this method is called only when a candidate is contacted. And that can only be done by a registered user

2020-09-22 11:35 UTC, palsch approved these changes

2020-09-23 09:45 UTC, merged